### ISSUE TITLE
kproject doesn't play well when integrated into an existing project with build.gradle.kts/settings.gradle.kts

### ISSUE THREAD

**Issue by Kietyo** [korlibs/kproject#11]
https://github.com/Kietyo/XenoECS

Say that I setup kproject for the above.
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/222956194-1b0acfb1-7fda-4ea1-8295-192be4569887.png">

If I'm developing locally and have a project that references the local XenoECS folder.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/222956234-01809da5-51e5-4503-9495-fb2ac898114e.png">

Then it creates a build.gradle in the XenoECS directory
<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/222956212-5e87ed20-4f96-4337-85e4-dce309f77642.png">

Which results in compilation errors when am developing for the XenoECS project:

<img width="960" alt="image" src="https://user-images.githubusercontent.com/5054996/222956257-5494ed16-09c0-42a2-a02d-d7094c4b2096.png">

I think this is because I use Kotlin script for gradle configs

**Comment by soywiz** [comment]
Covered here: https://github.com/korlibs/korge-hello-world-client-server/pull/3/files
