### ISSUE TITLE
Provide setting to always output .kts (kotlin gradle dsl) rather than groovy

### ISSUE THREAD

**Issue by Kietyo** [korlibs/kproject#20]
After using kotlin gradle dsl for awhile now I can't go back to using groovy.

I'm okay with any amount of performance hit for this (which I doubt will actually be that much for most users of kproject).

Also TBH I don't have much experience with groovy since it's hard to find out what settings are available when there's no auto complete.

**Comment by soywiz** [comment]
Why do you want that? Those build.gradle are autogenerated and .gitignored. You cannot modify them anyway since they are going to be regenerated

**Comment by Kietyo** [comment]
Ah okay.
