### ISSUE TITLE
Including kproject causes the project to build for android for some reason

### ISSUE THREAD

**Issue by Kietyo** [korlibs/kproject#21]
<img width="1280" alt="image" src="https://github.com/korlibs/kproject/assets/5054996/e9467681-3a17-4213-b8c6-a612dbbc9609">

Here's the repo:

https://github.com/Kietyo/ktruth

**Comment by Kietyo** [comment]
I think it's because gradle refreshing causes this AndroidManifest to be created maybe:

<img width="338" alt="image" src="https://github.com/korlibs/kproject/assets/5054996/0d762424-26a9-4ad0-bef4-492a851ca992">

**Comment by soywiz** [comment]
kproject generates all the kotlin targets by default.
You can limit the targets by adding a targets key like this in your `deps.kproject.yml`:
https://github.com/korlibs/korge-intellij-plugin/blob/946a95ad6d2a7798e46060635c43302d827bf3c4/deps.kproject.yml#L1

**Comment by soywiz** [comment]
Does providing the targets you want fixes the issue?

**Comment by Kietyo** [comment]
Will try and let u know when i can. Been busy with work.

**Comment by Kietyo** [comment]
works for me, thx!
